---
title: "project-checkpoint-2"
format: html
editor: visual
---

## Data Summary (creating a new column)

```{r}
library(gt)
library(tidyverse)

cases_month <- tuesdata$cases_month
cases_year <- tuesdata$cases_year

View(cases_month)
View(cases_year)
```

**Research Question: Which country and region have the most measles and rubella cases combined?**

```{r}
total_country_cases <- cases_year |>
  mutate(
    across(c(measles_total, rubella_total), as.numeric)) |> # convert columns to numbers
  group_by(region, country) |> # group by region and country
  summarize(
    total_measles = sum(measles_total),
    total_rubella = sum(rubella_total),
    .groups = "drop") |>
  mutate(
    total_cases = total_measles + total_rubella) |> # new column, measles and rubella cases combined
arrange(desc(total_cases)) # sorts from highest to lowest cases

total_country_cases |>
  head(10) |>
  gt() |>
  
  cols_label(
    region = "Region",
    country = "Country",
    total_measles = "Total Measles Cases",
    total_rubella = "Total Ruebella Cases",
    total_cases = "Total Combined Cases"
  ) 
```

Based on the data summary of the total combined cases of measles and rubella, India, China, and Madagascar are the top three countries (grouped by region) that have the most measles cases from the years 2018-2026.
